tasks:
  - name: setup
    init: |
      python -m venv ..
      source ../bin/activate
      python -m pip install -e ".[dev,docs,lint,test]"
    command: |
      source ../bin/activate
      jlpm
      jlpm build
