
name: Test

on:
  push:
    branches: main
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Base Setup
      uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

    - name: Install JupyterLite from the draft PR
      run: |
        # this is temporary
        # need this since installing from git in pyproject.toml does not trigger the build
        # of the JS assets
        TMP_DIR=$(mktemp -d -t jupyterlite-XXXXX)
        pushd ${TMP_DIR}
        git clone https://github.com/jtpio/jupyterlite
        cd jupyterlite
        git checkout move-pyolite
        pip install doit sphinx flit jupyter_core pkginfo
        doit build
        popd

    - name: Install dependencies
      run: |
        python -m pip install -e ".[dev,test]"

    - name: Run the tests
      run: |
        echo "skipping tests for now"
        # pytest
